apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ztrr7yfia-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ztrr7yfia-go 
  name: ztrr7yfia-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ztrr7yfia-go 
